title = "The evolutionary trends of grammatical gender in Indo-Aryan languages"

doi = "https://doi.org/10.1163/22105832-bja10011"

abstract = """
This paper infers the processes of development and change of grammatical gender in Indo-Aryan languages using phylogenetic comparative methods. 48 Indo-Aryan languages are coded based on 44 presence-absence features relating to gender marking on the verbs, adjectives, personal pronouns, demonstrative pronouns, and possessive pronouns. A Bayesian Reverse Jump Hyper Prior analysis, which infers the evolutionary dynamics of changes between feature values, gives results that are consistent with historical linguistic and typological studies on gender systems in Indo-Aryan languages and predicts the evolutionary trends of the features included in the dataset.
"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Marc Allassonni√®re-Tang", "Michael Dunn"]

# parts of the world
groups = ['Indo-European']  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@Allassonniere_Tang_2020"

# type of study
type = ['trait', 'asr']  # asr,criticism,d-statistic,dating,delta,distance,macroevolutionary,methodological,phylogenetic,phylogeography,qresidual,review,structure,tiger,trait,tutorial,
framework = ['likelihood', 'bayesian'] # distance,parsimony,likelihood,bayesian,network,statistical,other
# short description of the study, one line.
description = ""

# data
[data]

    notes = ""
    
    [data.gender]
    ntaxa = 48
    nchars = 44
    nsites = 44
    datatype = 'structural features'
    source = ''
    items = ''
    comment = ''

# published phylogenies
[phylogenies]
    [phylogenies.glottolog]
    source = '@Glottolog41'
    comment = ''


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.lamba]
    tool = 'unknown'
    model = ''
    details = ""
    data = ""
    times = 44

    [analysis.bayestraits]
    tool = 'bayestraits'
    model = 'multistate+rjhp'
    details = ""
    data = ""
    
[inferredages]
    
    notes = ""
    
    [inferredage.label]
    taxa = []
    age = "hpd(median, lower, upper)"
    units = "bp"
    notes = ""


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []