title = "Phylogenetic ancestral state reconstruction of bilabial trills in the languages of Malekula Island (Vanuatu), and the historical evolution of rare sound changes"

doi = "10.1093/jole/lzaf004"

abstract = """

"""

# authors in "Firstname Initial. Lastname" e.g. Simon J. Greenhill
authors = ["Benedict King", "Tihomir Rangelov", "Mary Walworth"]

# parts of the world
groups = []  # 'Austronesian', etc

# bibkey citation in sources.bib
bibkey = "@King_2025"

# type of study
type = []  # asr,criticism,d-statistic,dating,delta,distance,macroevolutionary,methodological,phylogenetic,phylogeography,qresidual,review,structure,tiger,trait,tutorial,
framework = [] # distance,parsimony,likelihood,bayesian,network,statistical,other
# short description of the study, one line.
description = ""

# data
[data]

    notes = ""
    
    [data.bantu]
    ntaxa = 95
    nchars = 100
    nsites = "?"
    datatype = 'lexical cognates'
    source = '@xxx'
    items = ''
    comment = ''

# published phylogenies
[phylogenies]
    [phylogenies.label]
    source = '@xxx'
    comment = ''


# date calibrations
[calibrations]

    notes = ""

    [calibration.label]
    taxa = []
    age = "" # x, normal(x, y), uniform(x,y), lognormal(x, y, z, realspace=True)
    units = "bp" # bp
    description = ""


# analysis information
[analysis]
    
    notes = ""
    
    [analysis.tree]
    tool = ''
    model = ''
    details = ""
    data = ""

[inferredages]
    
    notes = ""
    
    [inferredage.label]
    taxa = []
    age = "hpd(median, lower, upper)"
    units = "bp"
    notes = ""


[links]
phlorest = { title = "Phlorest Dataset", link = "" }
cldf = { title = "CLDF Dataset", link = "" }
dplace = { title = "D-PLACE Dataset", link = "" }
links = []